name: Java Maven Build and Test

on:
  push:
    branches:
      - dev
      - 'feature/**'# Change this to your default branch if it's different

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # You can change this to your desired Java version
          distribution: 'temurin'


      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Clean Workspace
        run: rm -rf target

      - name: Run Tests
        run: mvn -B test --file pom.xml

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports  # Adjust the path if your test reports are in a different directory